FROM ubuntu:jammy
RUN apt-get update && apt-get install -y default-jre libxalan2-java texlive ghostscript && rm -rf /var/lib/apt/lists/* && ln -s /usr/share/java/xalan2-2.7.2.jar /usr/share/java/xalan.jar
